# Generated by Django 5.1.2 on 2024-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Accountno', models.IntegerField(primary_key='accountno', serialize=False)),
                ('Mobileno', models.IntegerField()),
                ('Loanamount', models.IntegerField()),
                ('Branch', models.CharField(max_length=21)),
            ],
        ),
    ]
